spring:
  application:
    name: distributed_payment_ledger

  datasource:
    url: jdbc:postgresql://localhost:5432/deepak_DB
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect


  flyway:
    locations: classpath:db/migrations
    enabled: true

logging:
  level:
    org.flywaydb: DEBUG